
name: Publish NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore Telegraph/Telegraph.sln
    - name: Build
      run: dotnet build Telegraph/Telegraph.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test Telegraph/Telegraph.Test/Telegraph.Test.csproj
    - name: Publish Kvyk.Telegraph
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Telegraph/Telegraph/Telegraph.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
